apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None  # Headless service
  selector:
    app: mongodb  # Ensure this matches the label in the StatefulSet
  ports:
    - port: 27017
      targetPort: 27017
