apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster-africa
  region: af-south-1

nodeGroups:
  - name: nodegroup1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: true
