apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster-africa3
  region: af-south-1

nodeGroups:
  - name: nodegroup1
    instanceType: t3.small
    desiredCapacity: 4
    minSize: 2
    maxSize: 5
    volumeSize: 20
    ssh:
      allow: true
