# frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-yolo
  template:
    metadata:
      labels:
        app: frontend-yolo
    spec:
      containers:
      - name: frontend
        image: jorashid/yolo-frontend:v1.0.6
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-yolo
spec:
  selector:
    app: frontend-yolo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Expose to external access

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-yolo
  template:
    metadata:
      labels:
        app: backend-yolo
    spec:
      containers:
      - name: backend
        image: jorashid/yolo-backend:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-yolo:27017/yolomy"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-yolo
spec:
  selector:
    app: backend-yolo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Internal service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-yolo
  template:
    metadata:
      labels:
        app: mongodb-yolo
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-yolo
spec:
  selector:
    app: mongodb-yolo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP  # Internal service

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjusted storage size to 1Gi
  storageClassName: gp2  # Ensure your EKS uses a valid storage class
