apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-yolo
  template:
    metadata:
      labels:
        app: backend-yolo
    spec:
      containers:
      - name: backend
        image: jorashid/yolo-backend:v1.0.8
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/yolomy"
        resources:
          requests:
            memory: "50Mi"
            cpu: "150m"
          limits:
            memory: "100Mi"
            cpu: "200m"
