apiVersion: v1
kind: Service
metadata:
  name: backend-yolo
spec:
  selector:
    app: backend-yolo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Internal service
