apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-db
  labels:
    name: stateful-db
  annotations:
    description: "Creating stateful resource for the MongoDB database"
    
spec:
  serviceName: 'yolo-database'   # Fixed quote issue here
  replicas: 3                    # Optionally specify the number of replicas
  selector:
    matchLabels:
      app: mongodb
  
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017  # Corrected MongoDB port
          volumeMounts:
            - name: data
              mountPath: /data/db  # MongoDB default data path for storage

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 0.5Gi  
        storageClassName: standard  
