apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-yolo
  template:
    metadata:
      labels:
        app: frontend-yolo
    spec:
      containers:
      - name: frontend
        image: jorashid/yolo-frontend:v1.0.9
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "250m"
