apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-yolo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-yolo
  template:
    metadata:
      labels:
        app: frontend-yolo
    spec:
      containers:
      - name: frontend
        image: jorashid/yolo-frontend:v1.0.6
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
