apiVersion: v1
kind: Service
metadata:
  name: frontend-yolo-service
spec:
  selector:
    app: frontend-yolo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Expose frontend to external access
